spring.application.name=FraktalBackend
spring.datasource.url=jdbc:postgresql://localhost:5432/fraktaldb
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.main.allow-bean-definition-overriding=true
jwt.secret=fraktal-dev-secret-key-minimum-32-characters
jwt.expiration=3600000
app.frontend-url=http://localhost:3000
